### ISSUE TITLE
Using powershells send-mailmessage fails

### ISSUE THREAD

**Issue by christau** [ctabin/smtp4j#60]
Hi,
I currently have the problem that sending a mail via powershell does not work.
On the side of the smtp4j there's an exception thrown
`WARNUNG: Protocol Exception
ch.astorm.smtp4j.protocol.SmtpProtocolException: Unexpected end of stream (no more line)
	at ch.astorm.smtp4j.protocol.SmtpTransactionHandler.nextLine(SmtpTransactionHandler.java:169)
	at ch.astorm.smtp4j.protocol.SmtpTransactionHandler.readTransaction(SmtpTransactionHandler.java:128)
	at ch.astorm.smtp4j.protocol.SmtpTransactionHandler.execute(SmtpTransactionHandler.java:76)
	at ch.astorm.smtp4j.protocol.SmtpTransactionHandler.handle(SmtpTransactionHandler.java:53)
	at ch.astorm.smtp4j.SmtpServer$SmtpPacketListener.run(SmtpServer.java:281)
	at java.lang.Thread.run(Thread.java:748)`
Sender and receipient could be retrieved from the mail, but when it come to reading the DATA there's no more lines to read.
This is the command I send:
`Send-MailMessage -To recipient@mydomain -from sender@ydomain -Port 1025 -Subject 'An action is pending' -body 'Cheers, your admin' -SmtpServer "localhost"`  

When sending a mail via Java code everything works as expected.

Has anyone any clue what the problem is here?
I worked with version 3.1.0

Many thanks in advance,
chris

**Comment by ctabin** [comment]
Hi @christau,
I never tried `Send-MailMessage` in PowerShell, I guess there is something special in the protocol... Hopefully it does not send with smtps or starttls because that's not supported (at least yet).
I guess you are launching smtp4j in a Thread in your app ?

**Comment by christau** [comment]
Hi @ctabin ,
thanks for your reply. 
I'm using smpt4j as a kind of smtp relais to compensate the inability to use authentication of another app. 
But as you mentioned ssl, I may try to disable it explicitly. 
By the way, thanks very much for sharing your code, it just came in handy for my requirement.

**Comment by christau** [comment]
Hi @ctabin,
I think I found the spot where it goes wrong and made a PR that fixes it for me.
Best regards, chris

**Comment by ctabin** [comment]
Fixed by #61.

**Comment by christau** [comment]
Hi @ctabin,
I just realized that with the lastest version 3.1.2 the powershell line does not work in any way, also not with 3.1.0. 
When using the 3.0.1 with the patch everything works again. I'll look into the problem later this week and see if I can find it.
Cheers, -chris-

**Comment by christau** [comment]
Hi @ctabin, I think now I found the origin of the problem. 
When invoking `Send-MailMessage`, the command returns but the connection is kept open and no QUIT is sent. 
When executing this command another time, the previous connection is 'reused' and here the smtp transaction handler begins to stumble because a QUIT is expected before receiving another message. 
I could hack around this by resetting the members
`
    mailFrom=null;
    recipients=null;
    smtpMessageContent=null;
`
after the DOT command is sent and the message is created.
This is no longer working with versions > 3.0.1, because only if the QUIT is sent, the message gets created now.
I'm not really sure, but I think the smtp protocol allows receiving multiple e-mails in a session with finally sending QUIT and terminating the connection.
Can you agree with that?
If yes, we could extend the existing code. 
Best regards, -chris-
